// One-time migration: old Next.js repo -> this Jekyll site.
// Run from this directory: node migrate.mjs
import matter from 'gray-matter'
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  copyFileSync,
  statSync,
  rmSync,
} from 'fs'
import { join, basename } from 'path'

const OLD = '/Users/sebastien/dev/scastiel.dev'
const NEW = '/Users/sebastien/dev/new-scastiel.dev'

const ensureDir = (d) => mkdirSync(d, { recursive: true })

// Format a value that gray-matter parsed (Date or string) into YYYY-MM-DD.
const toYmd = (v) => {
  if (v instanceof Date) return v.toISOString().slice(0, 10)
  const s = String(v)
  const m = s.match(/^(\d{4}-\d{2}-\d{2})/)
  return m ? m[1] : s
}

const rewriteRelativePaths = (content, slug) => {
  return content
    // Markdown images/links: ](./x)  ->  ](/assets/posts/<slug>/x)
    .replace(/\]\(\.\//g, `](/assets/posts/${slug}/`)
    // Raw HTML: src="./x" and src='./x'
    .replace(/src="\.\//gi, `src="/assets/posts/${slug}/`)
    .replace(/src='\.\//gi, `src='/assets/posts/${slug}/`)
    // Legacy excerpt markers -> Jekyll's
    .replace(/<!--\s*readmore\s*-->/gi, '<!--more-->')
}

// Build front matter YAML by hand-dumping via gray-matter.stringify.
// Drop keys whose value is undefined/null (js-yaml refuses to dump undefined).
const dump = (data, body) => {
  const clean = {}
  for (const [k, v] of Object.entries(data)) {
    if (v !== undefined && v !== null) clean[k] = v
  }
  return matter.stringify(body, clean)
}

// ---------- 1. Articles (blog posts) ----------
const postsDir = join(OLD, 'data', 'posts')
const postSlugs = readdirSync(postsDir).filter((f) => f !== '.DS_Store')
let articleCount = 0
ensureDir(join(NEW, '_articles'))
for (const slug of postSlugs) {
  const dir = join(postsDir, slug)
  const indexFile = join(dir, 'index.md')
  if (!existsSync(indexFile)) continue
  const { data, content } = matter(readFileSync(indexFile))

  const fm = {
    title: data.title,
    date: toYmd(data.date),
    excerpt: data.excerpt,
  }
  if (data.cover) fm.cover = String(data.cover).replace(/^\.\//, `/assets/posts/${slug}/`)
  if (data.redirect_from) {
    fm.redirect_from = Array.isArray(data.redirect_from)
      ? data.redirect_from
      : [data.redirect_from]
  }
  if (data.lang) fm.lang = data.lang
  if (data.tags) fm.tags = data.tags

  const body = rewriteRelativePaths(content, slug)
  writeFileSync(join(NEW, '_articles', `${slug}.md`), dump(fm, body))
  articleCount++

  // Copy co-located assets (everything except index.md) to /posts/<slug>/
  const assets = readdirSync(dir).filter(
    (f) => f !== 'index.md' && f !== '.DS_Store',
  )
  if (assets.length) {
    const outDir = join(NEW, 'assets', 'posts', slug)
    ensureDir(outDir)
    for (const a of assets) {
      const src = join(dir, a)
      if (statSync(src).isFile()) copyFileSync(src, join(outDir, a))
    }
  }
}
console.log(`Articles: ${articleCount}`)

// ---------- 2. Books ----------
const booksDir = join(OLD, 'data', 'books')
const bookFiles = readdirSync(booksDir).filter((f) => f.endsWith('.md'))
ensureDir(join(NEW, '_books'))
const booksData = []
let bookPages = 0
for (const file of bookFiles) {
  const slug = file.replace(/\.md$/, '')
  const { data, content } = matter(readFileSync(join(booksDir, file)))
  const hasPage = Boolean(data.gumroadId)
  // The real cover image files live under /assets/book-covers/ (the /books/ path
  // in front matter never existed as a static file on the old site).
  const cover = data.cover ? String(data.cover).replace(/^\/books\//, '/assets/book-covers/') : data.cover
  booksData.push({
    slug,
    title: data.title,
    date: toYmd(data.date),
    cover,
    description: data.description,
    urls: data.urls || [],
    has_page: hasPage,
  })
  if (hasPage) {
    const fm = {
      title: data.title,
      date: toYmd(data.date),
      cover,
      description: data.description,
      urls: data.urls || [],
      redirect_from: [`/books/${slug}`],
    }
    writeFileSync(join(NEW, '_books', `${slug}.md`), dump(fm, content))
    bookPages++
  }
}
// Sort listing by date descending (newest first), like the old site.
booksData.sort((a, b) => b.date.localeCompare(a.date))
ensureDir(join(NEW, '_data'))
// Emit books.yml
const yamlEscape = (s) => `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
let yml = '# Generated by migrate.mjs — full book listing (drives /books page).\n'
for (const b of booksData) {
  yml += `- slug: ${b.slug}\n`
  yml += `  title: ${yamlEscape(b.title)}\n`
  yml += `  date: ${b.date}\n`
  yml += `  cover: ${yamlEscape(b.cover)}\n`
  yml += `  description: ${yamlEscape(b.description)}\n`
  yml += `  has_page: ${b.has_page}\n`
  yml += `  urls:\n`
  for (const u of b.urls) {
    yml += `    - label: ${yamlEscape(u.label)}\n`
    yml += `      url: ${yamlEscape(u.url)}\n`
  }
}
writeFileSync(join(NEW, '_data', 'books.yml'), yml)
console.log(`Books: ${booksData.length} total, ${bookPages} with pages`)

// ---------- 3. Projects ----------
const projectsDir = join(OLD, 'data', 'projects')
const projectFiles = readdirSync(projectsDir).filter((f) => f.endsWith('.md'))
ensureDir(join(NEW, '_projects'))
let projectCount = 0
for (const file of projectFiles) {
  const slug = file.replace(/\.md$/, '')
  const { data, content } = matter(readFileSync(join(projectsDir, file)))
  const fm = {
    name: data.name,
    description: data.description,
    // Stored as `link`, not `url`: a Jekyll collection document's `url` is its
    // own output URL, which would shadow this field in templates.
    link: data.url,
    started: toYmd(data.started),
    stack: data.stack || [],
    logo: data.logo
      ? String(data.logo).replace(/^\/projects\//, '/assets/projects/')
      : data.logo,
  }
  if (data.sold) fm.sold = true
  writeFileSync(join(NEW, '_projects', `${slug}.md`), dump(fm, content))
  projectCount++
}
console.log(`Projects: ${projectCount}`)

// ---------- 4. Assets ----------
const copyTree = (src, dst) => {
  ensureDir(dst)
  for (const entry of readdirSync(src)) {
    if (entry === '.DS_Store') continue
    const s = join(src, entry)
    const d = join(dst, entry)
    if (statSync(s).isDirectory()) copyTree(s, d)
    else copyFileSync(s, d)
  }
}
// All media lives under /assets/ (keeps the project root clean).
const publicDir = join(OLD, 'public')
ensureDir(join(NEW, 'assets'))
for (const entry of readdirSync(publicDir)) {
  if (entry === '.DS_Store') continue
  // Skip generated mirrors: posts/ (regenerated above) and feed/ (jekyll-feed)
  if (entry === 'posts' || entry === 'feed') continue
  const s = join(publicDir, entry)
  const d = join(NEW, 'assets', entry)
  if (statSync(s).isDirectory()) copyTree(s, d)
  else copyFileSync(s, d)
}
// Favicon / icons from src/app stay at the site root (browser/convention).
for (const icon of ['favicon.ico', 'icon.png', 'apple-icon.png']) {
  const s = join(OLD, 'src', 'app', icon)
  if (existsSync(s)) copyFileSync(s, join(NEW, icon))
}
console.log('Assets copied.')
console.log('Done.')
